/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recipy.system;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.AbstractBorder;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.AbstractBorder;

public class Createaccount extends javax.swing.JFrame {

  // private AbstractBorder circleBorder = new CircleBorder(); 
    
    
    
   // private BufferedImage image;
    
 

    public Createaccount() {
        initComponents();
     //   jLabel1.setBorder(circleBorder); 
    //    jLabel1.setForeground(new Color (0,0,0,0));
      //  jLabel1.setBackground(new Color (0,0,0,0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_img = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        L_password = new javax.swing.JPasswordField();
        L_RePassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        L_Email1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        Country = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 600));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255,80));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0), 2));
        jPanel1.setMinimumSize(new java.awt.Dimension(780, 570));
        jPanel1.setPreferredSize(new java.awt.Dimension(780, 570));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_img.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.add(lbl_img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel4.setFont(new java.awt.Font("Harrington", 3, 24)); // NOI18N
        jLabel4.setText("User Name :");
        jLabel4.setMaximumSize(new java.awt.Dimension(127, 31));
        jLabel4.setMinimumSize(new java.awt.Dimension(127, 31));
        jLabel4.setPreferredSize(new java.awt.Dimension(127, 31));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 150, -1));

        jLabel5.setFont(new java.awt.Font("Harrington", 3, 24)); // NOI18N
        jLabel5.setText("Email :");
        jLabel5.setMaximumSize(new java.awt.Dimension(72, 31));
        jLabel5.setMinimumSize(new java.awt.Dimension(72, 31));
        jLabel5.setPreferredSize(new java.awt.Dimension(72, 31));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 120, 50));

        jLabel7.setFont(new java.awt.Font("Harrington", 3, 24)); // NOI18N
        jLabel7.setText("Password:");
        jLabel7.setMaximumSize(new java.awt.Dimension(103, 31));
        jLabel7.setMinimumSize(new java.awt.Dimension(103, 31));
        jLabel7.setPreferredSize(new java.awt.Dimension(103, 31));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 150, -1));

        jLabel9.setFont(new java.awt.Font("Harrington", 3, 24)); // NOI18N
        jLabel9.setText("Already Have An Account ? Click Here To Login");
        jLabel9.setMaximumSize(new java.awt.Dimension(464, 31));
        jLabel9.setMinimumSize(new java.awt.Dimension(464, 31));
        jLabel9.setPreferredSize(new java.awt.Dimension(464, 31));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 550, 30));

        username.setBackground(new java.awt.Color(153, 102, 0,80));
        username.setFont(new java.awt.Font("Bradley Hand ITC", 3, 30)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0)));
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 470, 40));

        L_password.setBackground(new java.awt.Color(153, 102, 0,80));
        L_password.setFont(new java.awt.Font("Bradley Hand ITC", 3, 30)); // NOI18N
        L_password.setForeground(new java.awt.Color(255, 255, 255));
        L_password.setToolTipText("Enter Password");
        L_password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0)));
        jPanel1.add(L_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 470, 40));

        L_RePassword.setBackground(new java.awt.Color(153, 102, 0,80));
        L_RePassword.setFont(new java.awt.Font("Bradley Hand ITC", 3, 30)); // NOI18N
        L_RePassword.setForeground(new java.awt.Color(255, 255, 255));
        L_RePassword.setToolTipText("Enter Password");
        L_RePassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0)));
        jPanel1.add(L_RePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 470, 40));

        jButton1.setBackground(new java.awt.Color(153, 102, 0,80));
        jButton1.setFont(new java.awt.Font("Bradley Hand ITC", 3, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon3.png"))); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0), 3));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 40));

        jButton3.setBackground(new java.awt.Color(153,102,0,80));
        jButton3.setFont(new java.awt.Font("Harrington", 3, 24)); // NOI18N
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0), 3));
        jButton3.setLabel("Creat Account ");
        jButton3.setMaximumSize(new java.awt.Dimension(155, 31));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, 180, 50));

        jLabel10.setFont(new java.awt.Font("Harrington", 3, 24)); // NOI18N
        jLabel10.setText("Country :");
        jLabel10.setMaximumSize(new java.awt.Dimension(193, 31));
        jLabel10.setMinimumSize(new java.awt.Dimension(193, 31));
        jLabel10.setPreferredSize(new java.awt.Dimension(193, 31));
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 150, -1));

        L_Email1.setBackground(new java.awt.Color(153, 102, 0,80));
        L_Email1.setFont(new java.awt.Font("Bradley Hand ITC", 3, 30)); // NOI18N
        L_Email1.setForeground(new java.awt.Color(255, 255, 255));
        L_Email1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0)));
        jPanel1.add(L_Email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 470, 40));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Harrington", 3, 18)); // NOI18N
        jCheckBox1.setText("Show");
        jCheckBox1.setMaximumSize(new java.awt.Dimension(51, 23));
        jCheckBox1.setMinimumSize(new java.awt.Dimension(51, 23));
        jCheckBox1.setPreferredSize(new java.awt.Dimension(51, 23));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 80, -1));

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setFont(new java.awt.Font("Harrington", 3, 18)); // NOI18N
        jCheckBox2.setText("Show");
        jCheckBox2.setMaximumSize(new java.awt.Dimension(51, 23));
        jCheckBox2.setMinimumSize(new java.awt.Dimension(51, 23));
        jCheckBox2.setPreferredSize(new java.awt.Dimension(51, 23));
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 80, -1));

        jLabel1.setFont(new java.awt.Font("Harrington", 0, 14)); // NOI18N
        jLabel1.setText("         add imag...");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 102, 0), new java.awt.Color(153, 102, 0)));
        jLabel1.setMaximumSize(new java.awt.Dimension(150, 150));
        jLabel1.setMinimumSize(new java.awt.Dimension(150, 150));
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 150));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 150, 150));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-picture-24.png"))); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0), 3));
        jButton2.setMaximumSize(new java.awt.Dimension(24, 24));
        jButton2.setMinimumSize(new java.awt.Dimension(24, 24));
        jButton2.setPreferredSize(new java.awt.Dimension(24, 24));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 20, 20));

        jLabel11.setFont(new java.awt.Font("Harrington", 3, 24)); // NOI18N
        jLabel11.setText("Re_Password:");
        jLabel11.setMaximumSize(new java.awt.Dimension(193, 31));
        jLabel11.setMinimumSize(new java.awt.Dimension(193, 31));
        jLabel11.setPreferredSize(new java.awt.Dimension(193, 31));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 170, -1));

        Country.setBackground(new java.awt.Color(153, 102, 0,80));
        Country.setFont(new java.awt.Font("Harrington", 2, 14)); // NOI18N
        Country.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Palestine", "Syria", "Lebnan" }));
        Country.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0), 3));
        jPanel1.add(Country, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 130, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 760, 560));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/V2.gif"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(1050, 600));
        jLabel2.setMinimumSize(new java.awt.Dimension(1050, 600));
        jLabel2.setPreferredSize(new java.awt.Dimension(1050, 600));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        Login L= new Login();
        L.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Login L= new Login();
        L.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
public boolean isEmailExist(String ue) {
         boolean uExist = false;
        try {
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String ural ="jdbc:oracle:thin:@localhost:1521:xe";
            Connection con =  DriverManager.getConnection(ural,"c##hoom","123456");
            ResultSet rs;
            PreparedStatement ps= con.prepareStatement("SELECT * FROM us WHERE  email = ?");
            ps.setString(1, L_Email1.getText());
            rs = ps.executeQuery();
            if(rs.next()){
                uExist = true;
            }
       con.setAutoCommit(false);
//       con.commit();
       con.close();
        } catch (Exception ex) {
           
        }
             
        return uExist;
         
     }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
      try {
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
            String ural ="jdbc:oracle:thin:@localhost:1521:xe";
            Connection con =  DriverManager.getConnection(ural,"c##hoom","123456");
            PreparedStatement ps= con.prepareStatement("insert into us (username,email,passwords,country,image) values (?,?,?,?,?)");

            ps.setString(1,username.getText());
            ps.setString(2,L_Email1.getText());
            ps.setString(3,String.valueOf(L_password.getPassword()));
            ps.setString(4, (String) Country.getSelectedItem());
            ps.setString(5,jLabel1.getText());
            if(isEmailExist(L_Email1.getText()) ){
                JOptionPane.showMessageDialog(null, "Email already exists");

            }

            else {
                if(ps.executeUpdate() != 0){
                    JOptionPane.showMessageDialog(null, "Account created sucessfully");
                    con.setAutoCommit(false);
                    con.commit();
                    con.close();
                    Login log = new Login();
                    log.setVisible(true);
                    this.setVisible(false);
                }
                else
                JOptionPane.showMessageDialog(null, "Something is wrong");
            }

        } catch (Exception ex) {

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
            L_password.setEchoChar((char)0);
        }
        else{
            L_password.setEchoChar(('*'));
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox2.isSelected()){
            L_RePassword.setEchoChar((char)0);
        }
        else{
            L_RePassword.setEchoChar(('*'));
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("4 supported extensions", "jpg","jpeg","gif","png");
        fileChooser.setFileFilter(filter);
        int selected = fileChooser.showOpenDialog(null);
        if(selected == JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            String getSelectedImage = file.getAbsolutePath();
            JOptionPane.showMessageDialog(null, getSelectedImage);
            ImageIcon imIco = new ImageIcon(getSelectedImage);
            jLabel1.setText(getSelectedImage);
       /* try {
                BufferedImage bufferedImage = ImageIO.read(new File(getSelectedImage));
            
        } catch (IOException e) {
            e.printStackTrace();
        }*/
            Image imFit = imIco.getImage();
            Image imgFit = imFit.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
            jLabel1.setIcon(new ImageIcon(imFit));
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Createaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Createaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Createaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Createaccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Createaccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Country;
    private javax.swing.JTextField L_Email1;
    private javax.swing.JPasswordField L_RePassword;
    private javax.swing.JPasswordField L_password;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
