/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recipy.system;

import oracle.jdbc.driver.*;
import oracle.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
public class Login extends javax.swing.JFrame {
public static String email;
    public Login() {
        initComponents();
        email="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        L_Email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        L_Password = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        ForgetPassword = new javax.swing.JLabel();
        dont_hava_an_account = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 590));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(1050, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(1050, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255,80));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0), 2));
        jPanel2.setMinimumSize(new java.awt.Dimension(400, 800));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 800));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back.setBackground(new java.awt.Color( 153,102, 0,80));
        Back.setFont(new java.awt.Font("Harrington", 3, 24)); // NOI18N
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icon2.png"))); // NOI18N
        Back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0), 3));
        Back.setMaximumSize(new java.awt.Dimension(1009, 1009));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel2.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 40, 30));

        jLabel3.setFont(new java.awt.Font("Harrington", 3, 36)); // NOI18N
        jLabel3.setText("Email :");
        jLabel3.setMaximumSize(new java.awt.Dimension(108, 46));
        jLabel3.setMinimumSize(new java.awt.Dimension(108, 46));
        jLabel3.setPreferredSize(new java.awt.Dimension(108, 46));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 140, 50));

        L_Email.setBackground(new java.awt.Color(135, 102, 0,80));
        L_Email.setFont(new java.awt.Font("Bradley Hand ITC", 3, 30)); // NOI18N
        L_Email.setForeground(new java.awt.Color(255, 255, 255));
        L_Email.setToolTipText("Enter Your Email");
        L_Email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0)));
        jPanel2.add(L_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 350, 50));

        jLabel4.setFont(new java.awt.Font("Harrington", 3, 36)); // NOI18N
        jLabel4.setText("Password:");
        jLabel4.setMaximumSize(new java.awt.Dimension(157, 46));
        jLabel4.setMinimumSize(new java.awt.Dimension(157, 46));
        jLabel4.setPreferredSize(new java.awt.Dimension(157, 46));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 180, -1));

        L_Password.setBackground(new java.awt.Color(153, 102, 0,80));
        L_Password.setFont(new java.awt.Font("Bradley Hand ITC", 3, 30)); // NOI18N
        L_Password.setForeground(new java.awt.Color(255, 255, 255));
        L_Password.setToolTipText("Enter Password");
        L_Password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0)));
        L_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L_PasswordActionPerformed(evt);
            }
        });
        jPanel2.add(L_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 350, 50));

        jButton2.setBackground(new java.awt.Color( 153,102, 0,80));
        jButton2.setFont(new java.awt.Font("Harrington", 3, 24)); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0), 3));
        jButton2.setLabel("LOGIN");
        jButton2.setMaximumSize(new java.awt.Dimension(97, 39));
        jButton2.setMinimumSize(new java.awt.Dimension(97, 39));
        jButton2.setPreferredSize(new java.awt.Dimension(97, 39));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 120, 60));

        ForgetPassword.setBackground(new java.awt.Color(0, 0, 0,80));
        ForgetPassword.setFont(new java.awt.Font("Harrington", 3, 24)); // NOI18N
        ForgetPassword.setText("Forget Your Password ?");
        ForgetPassword.setMaximumSize(new java.awt.Dimension(235, 31));
        ForgetPassword.setMinimumSize(new java.awt.Dimension(235, 31));
        ForgetPassword.setName(""); // NOI18N
        ForgetPassword.setPreferredSize(new java.awt.Dimension(235, 31));
        ForgetPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForgetPasswordMouseClicked(evt);
            }
        });
        jPanel2.add(ForgetPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 290, -1));

        dont_hava_an_account.setBackground(new java.awt.Color(0, 0, 0,80));
        dont_hava_an_account.setFont(new java.awt.Font("Harrington", 3, 24)); // NOI18N
        dont_hava_an_account.setText("Dont Hava An Account ? Creat Account");
        dont_hava_an_account.setToolTipText("");
        dont_hava_an_account.setMaximumSize(new java.awt.Dimension(386, 31));
        dont_hava_an_account.setMinimumSize(new java.awt.Dimension(386, 31));
        dont_hava_an_account.setPreferredSize(new java.awt.Dimension(386, 31));
        dont_hava_an_account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dont_hava_an_accountMouseClicked(evt);
            }
        });
        jPanel2.add(dont_hava_an_account, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 470, -1));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255,80));
        jCheckBox1.setFont(new java.awt.Font("Harrington", 3, 14)); // NOI18N
        jCheckBox1.setLabel("Show");
        jCheckBox1.setMaximumSize(new java.awt.Dimension(51, 23));
        jCheckBox1.setMinimumSize(new java.awt.Dimension(51, 23));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 60, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 620, 440));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/V6 (1).gif"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(1050, 600));
        jLabel2.setMinimumSize(new java.awt.Dimension(1050, 600));
        jLabel2.setPreferredSize(new java.awt.Dimension(1050, 600));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 640));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:\
        Welcome W = new Welcome();
        W.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    private void L_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L_PasswordActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       try {
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());

            String ural ="jdbc:oracle:thin:@localhost:1521:xe";
            Connection con =  DriverManager.getConnection(ural," C##hoom","123456");
            PreparedStatement ps= con.prepareStatement("SELECT * FROM us WHERE  EMAIL = ? AND PASSWORDS =?");
            ResultSet rs;
            ps.setString(1, L_Email.getText());
            ps.setString(2, String.valueOf(L_Password.getPassword()));
            rs = ps.executeQuery();
            if(rs.next()){
                con.setAutoCommit(false);
                con.commit();
                con.close();
                if(L_Email.getText().equals("admin@gmail.com")){

                    Admin a = new Admin();
                    a.setVisible(true);
                    this.setVisible(false);
                }
                else{
                    email=  L_Email.getText();
                    // System.out.println(email);
                    User U = new User();
                    U.setVisible(true);
                    this.setVisible(false);

                }

            }
            else {
                JOptionPane.showMessageDialog(null, "please check again, something is wrong");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ForgetPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgetPasswordMouseClicked
        // TODO add your handling code here:
        ForgetPassword f = new ForgetPassword();
        f.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ForgetPasswordMouseClicked

    private void dont_hava_an_accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dont_hava_an_accountMouseClicked
        Createaccount c = new Createaccount();
        c.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_dont_hava_an_accountMouseClicked

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
            L_Password.setEchoChar((char)0);
        }
        else{
            L_Password.setEchoChar(('*'));
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel ForgetPassword;
    private javax.swing.JTextField L_Email;
    private javax.swing.JPasswordField L_Password;
    private javax.swing.JLabel dont_hava_an_account;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
